### ISSUE TITLE
Unexpected identifier on import when running test suite with jest.

### ISSUE THREAD

**Issue by RobertHosking** [koliseoapi/react-async-autocomplete#9] opened 2019-01-22 16:14 UTC
run `$ npx jest`
What's wierd is I'm only testing sagas. Seems like they are unrelated to the package.
```
  ● Test suite failed to run

    /path/to/app/node_modules/react-async-autocomplete/lib/main.js:10
    import ReactDOM from 'react-dom';
           ^^^^^^^^

    SyntaxError: Unexpected identifier

    > 1 | import Autocomplete from "react-async-autocomplete";
        | ^
      2 | import React, { Component } from "react";
      3 | import AutocompleteResult from './AutocompleteResult';

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:433:17)
      at Object.<anonymous> (/path/to/app/js/components/SearchBar.js:1:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.51s
Ran all test suites.
```

**Comment by icoloma** [comment] 2019-01-23 08:46
Seems like a duplicate of #4. `react-async-autocomplete` does not ship a transpiled version, please add  something like this to your jest config:

```js
transformIgnorePatterns: [
    'node_modules/(?!react-async-autocomplete)'
  ]
```

I'm closing as a duplicate, please reopen if I misunderstood something

**Closed by icoloma** 2019-01-23 08:46 UTC
